### ISSUE TITLE
Parameter value problem

### ISSUE THREAD

**Issue by NingYu0706** [GeWanying/shap-anti-spoofing#1]
Hi, I would like to ask you about a  problem with a parameter in the test.py file in 2D-spec. The function "asv_cal_accuracies(test_loader, net, device)" has 3 parameters, but later in the main function, "asv_cal_accuracies(protocol_file_path, data_path, Net, test_device, data_type='time_frame', dataset=19)" which has 5 parameter values, this place did not run successfully, I do not know what you have done here to deal with?

**Comment by GeWanying** [comment]
Hi,

I updated this file and it works fine on my side now. Please add your correct data path to the file and try.

This happens because I taylored the function "asv_cal_accuracies(test_loader, net, device)" for the experiment and forgot to change it in the main function. The original code is [here](https://github.com/ghuawhu/end-to-end-synthetic-speech-detection/blob/main/test.py), where protocol_file_path, data_type and dataset are required.

**Comment by NingYu0706** [comment]
> 你好，
> 
> 我更新了这个文件，现在它在我这边运行良好。请在文件中添加正确的数据路径并尝试。
> 
> 发生这种情况是因为我为实验定制了函数“asv_cal_accuracies(test_loader, net, device)”，却忘记在主函数中更改它。原始代码在[此处](https://github.com/ghuawhu/end-to-end-synthetic-speech-detection/blob/main/test.py)，其中需要 protocol_file_path、data_type 和 dataset。

I have been able to run it successfully. Of course, the "test.py" function in the 1D-waveform file has the same problem, and you can renew it as the same. Thank you very much for your answer. Your work helps me a lot.

**Comment by NingYu0706** [comment]
I have been able to run it successfully. Of course, the "test.py" function in the 1D-waveform file has the same problem, and you can renew it as the same. Thank you very much for your answer. Your work helps me a lot.

**Comment by GeWanying** [comment]
Of course, I will update it soon.

Glad to hear that, let me know if you meet other problems, and any discussion is welcome.
